header_pages:
- FreeSoftware.md

title: GNS Game Design

style: dark
listen_for_clients_preferred_style: true

footer: 'Copyright (C) Jack Meng (exoad) 2023'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
