title: "GNS Game Design"
bye_message: "copyright (C) Jack Meng (exoad) 2023"
url: "https://gns-gamedesign.github.io"
disqus: exoad
baseurl: "/info/"
nick: "design!"
nick: "gjuniioor"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "gjuniioor"
blog:
    server: "wordpress.com"
    nick: "gjuniioor"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"


markdown: kramdown
permalink: /:categories/:title/
remote_theme: gildasio/clyell
