title: Desin
author: "GNS Game Design"
url: "https://gns-gamedesign.github.io/info/"
description: "Official landing page for the GNS Game Design Club"
favicon: "./favicon.png"

markdown: kramdown
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home"
  show_copyright: false
  show_reading_time: true
