title: "GNS Game Design"
bye_message: "copyright (C) Jack Meng (exoad) 2023"
url: "https://gns-gamedesign.github.io"
disqus: exoad
baseurl: "/info/"
nick: "desin!"

markdown: kramdown
permalink: /:categories/:title/
